  # web:
  #   build: .
  #   ports:
  #     - '3000:3000'
  #   depends_on:
  #     database:
  #       condition: service_healthy
  #   restart: on-failure:3
  #   networks:
  #     - node-network
  #   env_file: .env
volumes:
  dbdata:

networks:
  node-network:
    driver: bridge
